use car_service_app;

-- CREATE QUERIES

CREATE TABLE CUSTOMER (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(100) NOT NULL,
    ADDRESSLINE1 VARCHAR(255),
    ADDRESSLINE2 VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE,
    PHONENUMBER VARCHAR(15) NOT NULL,
    PASSWORDHASH VARCHAR(255) NOT NULL,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VEHICLE (
    VEHICLEID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMERID INT,
    VEHICLEBRANDNAME VARCHAR(50),
    VEHICLEMODELNAME VARCHAR(50),
    VEHICLEREGISTRATIONNUMBER VARCHAR(20) UNIQUE,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
        ON DELETE CASCADE
);

CREATE TABLE SERVICE (
    SERVICEID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICENAME VARCHAR(100) UNIQUE,
    SERVICEDESCRIPTION VARCHAR(255)
);

CREATE TABLE VENDOR(
    VENDORID INT PRIMARY KEY AUTO_INCREMENT,
    BUSINESSNAME VARCHAR(150),
    OWNERNAME VARCHAR(100),
    PHONENUMBER VARCHAR(15) NOT NULL UNIQUE,
    ADDRESSLINE VARCHAR(255),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PINCODE VARCHAR(10),
    GSTNUMBER VARCHAR(15),
    PASSWORDHASH VARCHAR(255) NOT NULL,
    ISVERIFIED TINYINT DEFAULT 0,
    ISACTIVE TINYINT DEFAULT 1,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VENDORSERVICE(
    VENDORSERVICEID INT PRIMARY KEY AUTO_INCREMENT,
    VENDORID INT,
    SERVICEID INT,
    PRICE DECIMAL(10,2) NOT NULL,
    ISACTIVE TINYINT DEFAULT 1,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (VENDORID, SERVICEID),

    FOREIGN KEY (VENDORID) REFERENCES VENDOR(VENDORID)
        ON DELETE CASCADE,
    FOREIGN KEY (SERVICEID) REFERENCES SERVICE(SERVICEID)
        ON DELETE CASCADE
);

INSERT INTO SERVICE (SERVICENAME, SERVICEDESCRIPTION)
VALUES ("CAR WASH", "GET YOUR CAR WASHED BY THE PROFESSIONALS");

SELECT SERVICEID as id, SERVICENAME as name FROM SERVICE
select * from CUSTOMER



