use car_service_app;

-- CREATE QUERIES

CREATE TABLE CUSTOMER (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(100) NOT NULL,
    ADDRESSLINE1 VARCHAR(255),
    ADDRESSLINE2 VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE,
    PHONENUMBER VARCHAR(15) NOT NULL,
    PASSWORDHASH VARCHAR(255) NOT NULL,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VEHICLE (
    VEHICLEID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMERID INT,
    VEHICLEBRANDNAME VARCHAR(50),
    VEHICLEMODELNAME VARCHAR(50),
    VEHICLEREGISTRATIONNUMBER VARCHAR(20) UNIQUE,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
        ON DELETE CASCADE
);

CREATE TABLE SERVICE (
    SERVICEID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICENAME VARCHAR(100) UNIQUE,
    SERVICEDESCRIPTION VARCHAR(255)
);
ALTER TABLE SERVICE ADD ICON VARCHAR(50);
UPDATE SERVICE SET icon = 'FaCar' WHERE SERVICENAME = 'CAR WASH';
UPDATE SERVICE SET icon = 'FaCar' WHERE SERVICENAME = 'OIL CHANGE';


CREATE TABLE VENDOR(
    VENDORID INT PRIMARY KEY AUTO_INCREMENT,
    BUSINESSNAME VARCHAR(150),
    OWNERNAME VARCHAR(100),
    PHONENUMBER VARCHAR(15) NOT NULL UNIQUE,
    ADDRESSLINE VARCHAR(255),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PINCODE VARCHAR(10),
    GSTNUMBER VARCHAR(15),
    PASSWORDHASH VARCHAR(255) NOT NULL,
    ISVERIFIED TINYINT DEFAULT 0,
    ISACTIVE TINYINT DEFAULT 1,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VENDOR_SERVICE(
    VENDORSERVICEID INT PRIMARY KEY AUTO_INCREMENT,
    VENDORID INT,
    SERVICEID INT,
    PRICE DECIMAL(10,2) NOT NULL,
    ISACTIVE TINYINT DEFAULT 1,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (VENDORID, SERVICEID),

    FOREIGN KEY (VENDORID) REFERENCES VENDOR(VENDORID)
        ON DELETE CASCADE,
    FOREIGN KEY (SERVICEID) REFERENCES SERVICE(SERVICEID)
        ON DELETE CASCADE
);

INSERT INTO SERVICE (SERVICENAME, SERVICEDESCRIPTION)
VALUES ("CAR WASH", "GET YOUR CAR WASHED BY THE PROFESSIONALS");

SELECT SERVICEID as id, SERVICENAME as name FROM SERVICE
select * from VENDOR_SERVICE

SELECT S.SERVICEID as id, S.SERVICENAME as name FROM SERVICE S inner join VENDOR_SERVICE VS 
 ON s.SERVICEID = vs.SERVICEID where VENDORID=3
DELETE FROM VENDOR WHERE VENDORID = 1

select * from CUSTOMER


SELECT SERVICEID as id, SERVICENAME as name,ICON as serviceicon FROM SERVICE

update vendor set isverified =1 where vendorid=3

SELECT DISTINCT v.*
      FROM vendor v
      JOIN vendor_service vs ON v.VENDORID = vs.VENDORID
      WHERE vs.SERVICEID = 2
      
      
CREATE TABLE BOOKING_STATUS(
		BOOKINGSTATUSID INT PRIMARY KEY AUTO_INCREMENT,
        BOOKINGSTATUSNAME VARCHAR(25)
        )
        
CREATE TABLE SERVICE_TYPE(
	SERVICETYPEID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICETYPENAME VARCHAR(50)
    )
    
CREATE TABLE VENDOR_SERVICE_TYPE(
	VENDORSERVICETYPEID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICETYPEID INT,
    VENDORSERVICEID INT,
    FOREIGN KEY (SERVICETYPEID) REFERENCES SERVICE_TYPE(SERVICETYPEID)
        ON DELETE CASCADE,
	FOREIGN KEY (VENDORSERVICEID) REFERENCES VENDOR_SERVICE(VENDORSERVICEID)
        ON DELETE CASCADE
        )
      
CREATE TABLE BOOKING (
    BOOKINGID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT,
    VENDORSERVICEID INT,
    BOOKINGSTATUSID INT,
    VEHICLEID INT,
    BOOKINGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    SCHEDULEDDATE DATETIME,
    SERVICETYPEID INT,
    TOTALAMOUNT DECIMAL(10,2),
    ADDRESS TEXT,
    NOTE TEXT,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY (VENDORSERVICEID) REFERENCES VENDOR_SERVICE(VENDORSERVICEID),
    FOREIGN KEY (BOOKINGSTATUSID) REFERENCES BOOKING_STATUS(BOOKINGSTATUSID),
    FOREIGN KEY (SERVICETYPEID) REFERENCES SERVICE_TYPE(SERVICETYPEID),
    FOREIGN KEY (VEHICLEID) REFERENCES VEHICLE(VEHICLEID)
);


CREATE TABLE BOOKING_STATUS_HISTORY (
    BOOKINGSTATUSHISTORYID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKINGID INT NOT NULL,
    BOOKINGSTATUSID INT NOT NULL,
    CHANGEDAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CHANGEDBY ENUM('CUSTOMER', 'VENDOR', 'ADMIN') NULL,
    REMARKS TEXT NULL,
    FOREIGN KEY (BOOKINGID) REFERENCES BOOKING(BOOKINGID),
    FOREIGN KEY (BOOKINGSTATUSID) REFERENCES BOOKING_STATUS(BOOKINGSTATUSID)
);

SELECT DISTINCT vs.*
      FROM vendor v
      JOIN vendor_service vs ON v.VENDORID = vs.VENDORID
      -- JOIN VENDOR_SERVICE_TYPE VST ON VS.VENDORSERVICEID=VST.VENDORSERVICEID
      -- JOIN SERVICE_TYPE ST ON VST.SERVICETYPEID=ST.SERVICETYPEID
      WHERE vs.VENDORSERVICEID = 1
      
      select * from customer
